### PR TITLE
Matches with changes in Maliput: Lane::ToLanePosition.

### PR DESCRIPTION
**Pull request by francocipollone**
Related to https://github.com/maliput/maliput/issues/496

### Summary

Matches with https://github.com/maliput/maliput/pull/521

action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b4f12ba16f95b45495362ae94202e810/raw/4d8ef8ec3fe272ca0619366ba2f389a934ca1aa0/maliput_multilane.repos

### CODE REVIEW

**Comment by francocipollone** [comment]
Some tests are failing because of change in behaviour. Now working on fixing them and adding some cases to fully test the api.

**Review by agalbachicar — COMMENTED** [review]
Please, add tests here.

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
